### ISSUE TITLE
I didn't look into the project but I tried to nitpick it anyway

### ISSUE THREAD

**Issue by ColleagueRiley** [prcastro/zeroGL#34]
This is a minor nitpick, isn't it a little disingenuous to claim your library has zero dependencies when all you did was pack the libraries required into zeroGL? For example, one of the libraries, SDL, is a decently sized library. 

You could easily solve this problem by changing the wording to 'zero external dependencies' instead and then explaining that the dependencies are packaged in. This is what Raylib does.

**Comment by ColleagueRiley** [comment]
"On other systems, just install SDL v2.28.2"

Huh

**Comment by ColleagueRiley** [comment]
My mistake, SDL is only used for the example code.

**Comment by prcastro** [comment]
Exactly! The zerogl.h is a zero-dependency lib, but to show stuff on screen I used SDL on the demo (main.c). The user can use any other library to present the framebuffer on screen and zeroGL doesn't provide any code to do that.
